### ISSUE TITLE
Circular reference between BrowserTest and NgBrowserTest

### ISSUE THREAD

**Issue by sglebs** [fhoeben/hsac-fitnesse-fixtures#11]
There is a circular reference (bad) between a superclass and its subclass. BrowserTest has an instance variable which is an NgBrowserTest (its subclass). This means that an instance of an NgBrowserTest will also have a second instance like itself, inherited from the superclass.

**Comment by fhoeben** [comment]
Actually it NgBrowserTest does not have an instance like itself. The instance is only created in `BrowserTest.waitForAngularIfNeeded()' which is never invoked for an NgBrowserTest, since that overrides `waitForAngularIfNeeded()` without calling `super.waitForAngularIfNeeded(method)`

But I admit it is not pretty and hard to read. Would you prefer the solution where `ngBrowserTest = (NgBrowserTest) this;` is if this is an instance of NgBrowserTest? It would make no difference in real-life at the moment, but it prevents any future issue when somebody would update NgBrowserTest call  `super.waitForAngularIfNeeded(method)`
