### ISSUE TITLE
Browser Test Question: Using heuristics on input elems without title attribute

### ISSUE THREAD

**Issue by bzon** [fhoeben/hsac-fitnesse-fixtures#113]
Hi,

I'm using this [petclinic project](https://github.com/spring-petclinic/spring-petclinic-rest) for a sample demo of browser testing.

I wanted to demo how to input using a heuristic way with (see screenshot below):

<img width="952" alt="screen shot 2017-02-20 at 5 54 19 am" src="https://cloud.githubusercontent.com/assets/19391568/23107028/10f78d4a-f731-11e6-9ff4-4ab46728bddc.png">

So I would like it to be like this:
```bash
|script|browser test                 |
|open  |http://localhost:9966/petclinic/owners|
|click |Find owners                  |
|click |Add Owner                    |
|enter |John           |as|First Name|
|enter |Doe            |as|Last Name |
|enter |Eastwood       |as|Address   |
|enter |City           |as|City      |
|enter |1929292        |as|Telephone |
|click |Add Owner|
|show  |take screenshot|result       |
```

The problem is it doesn't work, it times out.   
I have to use the Technical Selector way of testing like this:  
```bash
|script|browser test                                 |
|open  |http://localhost:9966/petclinic/owners|
|click |Find owners                                  |
|click |Add Owner                                    |
|enter |John           |as|xpath=//*[@id='firstName']|
|enter |Doe            |as|xpath=//*[@id='lastName'] |
|enter |Eastwood       |as|xpath=//*[@id='address']  |
|enter |City           |as|xpath=//*[@id='city']     |
|enter |1929292        |as|xpath=//*[@id='telephone']|
|click   |xpath=//*[@id='add-owner-form']/div[2]/div/button|                                                          |
|show  |take screenshot|result                       |
```

Thanks in advance~

**Comment by fhoeben** [comment]
The heuristics cannot find the input elements because the HTML contains 'labels' with the texts you want to use, but these are not properly connected/linked to the inputs. And since the labels are found the heuristic does not check other options (like the 'title' attribute on the inputs).

The label for 'First Name' should have contained an 'for' attribute linking it to the input with id 'firstName', or the 'div' containing the input should have been nested inside the label element. See https://www.w3.org/wiki/HTML/Elements/label#Point or https://www.w3schools.com/tags/tag_label.asp:
```
<label for="firstName" class="col-sm-2 control-label">First Name</label>
```

By a quick look at https://github.com/spring-petclinic/spring-petclinic-rest/blob/master/src/main/webapp/WEB-INF/tags/inputField.tag suggests that the html rendered by the 'inputField' tag could be better.... (Maybe they could use `form:label` to generate the label element and then use a runtime expression to give it a correct 'for' attribute?)

I expect a simple `|click|Add Owner|` does work, instead of the xpath based approach?

**Comment by bzon** [comment]
@fhoeben yep click Add Owner does work. Thanks for clarifying the heuristic approach. I may have to modify the jsp then. I will get back with my update.

**Comment by fhoeben** [comment]
If you can't get the HTML updated I would suggest using an 'id-based' technical selector, instead of an xpath. The test will be faster and the wiki page at least as readable. E.g.
```
|enter |John           |as|id=firstName|
```

**Comment by bzon** [comment]
Thanks man. Closing this one.
