### ISSUE TITLE
In JsonHttpTest special characters result in invalid message

### ISSUE THREAD

**Issue by pvreeuwijk** [fhoeben/hsac-fitnesse-fixtures#118]
When I post a message using JsonHttpTest containing special characters ( such as "BirthName": "Brontë" ), the message gets rejected due to parse errors. Posting the same message using Postman is accepted.
content type is: application/json

**Comment by keetron** [comment]
This looks similar to https://github.com/unclebob/fitnesse/issues/995

Please do as suggested by fhoeben:

> Adding !define slim.port {0} to .FitNesse.SuiteAcceptanceTests.SuiteSlimTests fixes the problem and makes the test green.

In your case, add to the top level suite will probably fix it.

**Comment by fhoeben** [comment]
I'm afraid the workaround suggested by @keetron will not address this problem, since the problem does not seem to be on the FitNesse side of things, but the actual system being tested rejects the message sent.

What I think might be happening is that the character set being used to send the message by JsonHttpTest is different from what is sent by Postman (and expected by the application being tested). 

How is the value being posted generated/specified? Is it set via the wiki using 'set value for' and then being sent as 'post values as json to', or is it sent using 'post to', or is it sent using 'post template to', or using 'post values to', or ...?

I believe all of these might influence which bytes actually end up in the call to the receiving service. As far as I recall of the top of my head json http test will always post using the UTF-8 character set (which I believe is the default (only?) character set for JSON). 

Do you know which character encoding the receiving application expects.

**Comment by fhoeben** [comment]
Which operating machine are you running FitNesse on?

**Comment by fhoeben** [comment]
When I try a simple local test on my mac there is no problem receiving the special characters. 

When you state the content type is 'application/json', do you mean you set that using a header 'Content-type' or that you used the 'set content type' method of json http test, or ... ?
Does the problem persist if you modify the content type to 'application/json; charset=utf-8'?

Can you provide some more detail (i.e. a sample test page, OS used in FitNesse and for REST server, which locale you have configured your FitNesse machine)?

**Comment by fhoeben** [comment]
I found how the encoding could go wrong: if you used the `|set content type|application/json|` the characters are sent using 'ISO-8859-1' which apparently the default http character encoding (but incorrect for json, which requires unicode).

As a workaround I suggest you replace the 'set content type' line with `|set value|application/json|for header|Content-Type|`, which will set the header but use UTF-8 as encoding. Alternatively you could also replace it with: `|set content type|application/json; charset=utf-8|`.

I made a change, to be included in the next release, which will default the content type to 'application/json; charset=utf-8' when either 'post values as json to' or 'put values as json to' is used.

**Comment by pvreeuwijk** [comment]
thanks!
