### ISSUE TITLE
Question: How to fail test if API did not return a response in x amount of time?

### ISSUE THREAD

**Issue by bzon** [fhoeben/hsac-fitnesse-fixtures#119]
I've read about setting the slim.timeout but it doesn't seem to work in my case. It even hangs for like an hour assuming the API I'm testing is really bad.

**Comment by bzon** [comment]
When running the test via command line I'm not getting stuck forever unlike when testing it the ui.

This is the actual result and the reason why it hangs for a long time when running in the ui.

```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

**Comment by fhoeben** [comment]
So you are able to send a request to the API your are testing, but then it just takes a really long time before it sends an answer. And when you do finally get an answer it is an error message (the html you posted) with a 504 response status?

How do you run from the command line?

I believe no maximum is configured for waiting for a request to complete, so at the moment there is no way to configure via the wiki that tests should fail if no response is received after X seconds.

In code it is not hugely complex, you would need to configure your own Apache HttpClient, with a default request configuration containing the 'socket timeout' of your choice, and supply that to `nl.hsac.fitnesse.fixture.util.HttpClient.setHttpClient()`

If, like you said, the API should not need that long to provide a response I believe you have identified an issue with the API: make sure that gets fixed instead of spending a lot of time making your test deal with it nicely...

**Comment by bzon** [comment]
Yes it takes a very long time when running it from the web ui and I will have to forcely stop it by click other pages. 

When using the java -jar cli or just it has no problem getting the gateway error right away. Even curl command tends to timeout but works (not most of the time) when added some options.

We are using a Fitnesse web server where all test pages are deployed by a CI server. We run test using Jenkinns by utilising that webserver's fitnesse jar cli. 

Thanks for the advice!

**Comment by fhoeben** [comment]
Have you considered running the tests using the jUnit runner from the CI server, like suggested in the README.md (or HsacExamples) of this project? Can you explain why you prefer the cli?

Can this issue be closed?

**Comment by bzon** [comment]
We wanted to preserve the test result history in the fitnesse server that is why we run the cli there. Test result history in the ui helps us identify what went wrong in the test and collect metrics out of it. 

We installed six42 jdbcslim plugin to work with your plugin for creating test data using fitnesse. Will maven still work? 

Thanks!

Closing the issue*

**Comment by fhoeben** [comment]
I see no reason that the fixtures by six42 should affect the jUnit runner. But I have not tried.

The jUnit run produces test results in xml and html format which a CI server can normally save for you. The (surefire) xml format is stored without additional config by Jenkins and TeamCity, in my experience. To show/keep the HTML reports some additional (simple) configuration is needed to tell the server where they are after a build/job. That's what I have done in the past.
