### ISSUE TITLE
Firefox browser process zombies on Centos 7

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#122]
A UNIX zombie process happens when the Firefox browser is started by FitNesse, and the parent (FirefoxDriver?) does not do a wait system call to remove Firefox from the process table when it exits.

Is there a way to ensure that a wait system call is executed when stopping the Firefox driver at the end of a FitNesse Browser Test?

**Comment by fhoeben** [comment]
Do you know what Java command should be executed exactly to remove the proces from the process table? The normal way to stop a Selenium webdriver is to call `close()` on it. That is what happens when you stop the driver by having a 'SuiteTearDown' with the content below. I assume you have that page in your project?

```
|script|selenium driver setup|
|stop driver                 |
```

**Comment by violinner** [comment]
Yes, I have the page, and the "SeleniumDriverSetup" test table.  I have confirmed that "stopDriver()" is being called.  Down the line, it is calling the browser to terminate (FireFoxDriver.quit()).

I see the connection being dropped, but I do not see anywhere that the caller is waiting for the remote process to exit.  If the Firefox process hangs on past the end of the test, a UNIX Zombie process will be created.  

This looks like a Selenium problem.
