### ISSUE TITLE
Disabling file save dialog for FireFox

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#125]
Testing on a headless firefox browser in UNIX, I need to disable the platform-specific pop-up dialog that asks to save or open a file, when I click on a link that downloads an Excel Spreadsheet file.  My objective is to save the ressponse to the files/downloads directory automatically, but so far it fails on the last step.

The following configuration saves a downloaded XLS file to the /tmp file as a ".part" file, but fails to move to the configured download directory.  I am wondering what is missing?

 |script |map fixture    |
 |set value      |2| for |browser.download.folderList|
 |set value      |false| for |browser.download.manager.showWhenStarting|
 |set value      |${PWD}/FitNesseRoot/files/downloads/| for |browser.download.dir|
 |set value      |!-application/vnd.openxmlformats-officedocument.spreadsheetml.sheet-!| for |browser.helperApps.neverAsk.saveToDisk|
 |$firefoxprofile=|copy map|

 |script |selenium driver setup|
 |start driver for|firefox       |with profile   | $firefoxprofile       |

**Comment by fhoeben** [comment]
I'm sorry, I don't have experience with downloading this way. So I don't know how you could configure Firefox to download to a specific directory instead of /tmp.

Is there any specific reason you use this approach to downloading instead of the `download <link>` command of BrowserTest which will download to the wiki's files section?
This bypasses the browser's (platform specific) 'save as' window but use Java to download the specific link found by the browser. So in my experience this works with all browsers (as the browser just has to supply the URL but not perform the actual download).

To have a hyperlink in your test report to the downloaded file create a line like (assuming the link to download the Excel has the text 'Download as Excel'):
`|show|download|Download as Excel|`

If you assign the download result to a slim variable (e.g. `|$excel=|download|Download as Excel|`) you can then use the downloaded file for other purposes (e.g. uploading using `select file <file> for <file input>` or manipulation using FileFixture).

**Comment by violinner** [comment]
Thanks for answering!
The application I am testing uses an angular-js export function that is fired on an onclick event on an HTML element, in this case, a button.

I am uncertain how to wire the browser export to an http request, since there is no href on the page.
As I understand it, the file export invokes a connection between Firefox and the OS, which pops up a dialog box to "save, open, or cancel", unless Firefox is properly configured to automatically save the file.

I am not getting the 
 |script |map fixture |
command to skip the download dialog, and using ImageMagic to get a screenshot, it still pops up.

**Comment by violinner** [comment]
I am not sure why the Firefox profile is not working.  However, there is a preference initialization file,
"all-redhat.js", which can be initialized with the same preferences from the map (above), and that works.

**Comment by fhoeben** [comment]
I may understand why the map fixture is not working. The keys have dots in them. I believe the map fixture is converting the single keys to nested maps, which is not what you need. (Similar to #127).

**Comment by fhoeben** [comment]
The latest version of the code (after https://github.com/fhoeben/hsac-fitnesse-fixtures/commit/60e25c7f30c2259a81373e1d85711b7e8b40ec05) can maybe address your problem. If you change the first table in wiki to:
```
|script                                |map fixture                                                                                                        |
|expand periods in names to nested maps|false                                                                                                              |
|set value                             |2                                                                    |for|browser.download.folderList              |
|set value                             |false                                                                |for|browser.download.manager.showWhenStarting|
|set value                             |${PWD}/FitNesseRoot/files/downloads/                                 |for|browser.download.dir                     |
|set value                             |!-application/vnd.openxmlformats-officedocument.spreadsheetml.sheet-!|for|browser.helperApps.neverAsk.saveToDisk   |
|$firefoxprofile=                      |copy map                                                                                                           |

```

**Comment by keetron** [comment]
I was worried about backwards compatibility as some of my tests use nested
maps so I am happy with this elegant design.

Op 14 apr. 2017 16:03 schreef "Fried Hoeben" <notifications@github.com>:
