### ISSUE TITLE
Question: How to use conditional actions for browser testing

### ISSUE THREAD

**Issue by bzon** [fhoeben/hsac-fitnesse-fixtures#129]
An example scenario would be:
```
|script|browser test|
|open|https://www.examplepage.com|
|click|expand side bar button|
|click|something inside the side bar|
```
If the current page side bar is already open (because somehow it is unpredictably opening and sometimes its not opened) do not look for or click the side bar button.. because clicking that button would just close the side bar and fails the rest of the test! 

If this is written in code, I would check the class value if it is on "active open" first before trying to click the "expand side bar button".. or like ensuring that the "side bar" is toggled.

Thanks!

**Comment by keetron** [comment]
If a webpage is not acting predictable it is a bug in the webpage that should not be resolved in the test. Therefor the `try` function or something like `if...else` is not implemented in the test framework. Best you figure out what the conditions are that open or close the sidebar, it could be caching or a stray cookie?

**Comment by fhoeben** [comment]
@keetron is right: in an ideal situation one should control the application being tested and therefore be able to rely on the sidebar either being there or NOT being there. So in principle there is no need for an 'if'.
BUT, as we all know, in practice things might be a bit more troublesome so there are ways to deal with this. They are not ideal, but sometime can help:
- for full control: create your own subclass of browser test and add a method (e.g. `ensureSidebarIsExpanded`) that contains the code like you describe it (if not currently open, click expand side bar)
- alternatively (staying in the wiki) you might be able to build a solution using `clickIfAvailable` and Slim script's 'show keyword'. Something like `|show|click if available|xpath=\\div[@class='closedSidebar']\..\button|`, which finds the button to click only if the side bar is currently closed (and the show keyword ensures the test result is not affected by whether the button is found or not). 

If you use the route of 'click if available' you probably also want to add separate control of the time browser test spends looking/waiting for the button, so that you don't have a long wait when the sidebar is already closed. Normally browser test will search for an element for 10 seconds before deciding it cannot find it. For a test like this you probably want to store the current wait time in a variable, reduce the wait time to a short period (e.g. 1 second), use click if available, and then restore the timeout to the previous value. Retrieving and setting the timeout can be done using `seconds before timeout`. 
This is quite a bit of logic to handle a conceptually simple 'ensure sidebar is open', so this should at least be put in a scenario, but making a Java method might be an even better idea. This complexity should not be repeated in multiple test pages...

**Comment by bzon** [comment]
@fhoeben the |show|click if available| on class has helped me!

And yes, we should find the root cause why the side bar is toggling unpredictably.

Thanks a lot for the answer guys!
