### ISSUE TITLE
Clone project is huge (4Gb)

### ISSUE THREAD

**Issue by keetron** [fhoeben/hsac-fitnesse-fixtures#130]
When cloning the project, it takes super long on my wifi and I found it is because the .pack file in the .git folder is 4Gb large. I do not feel this project has the codebase to allow for 4Gb?

**Comment by fhoeben** [comment]
You are absolutely right. I had not noticed it, since I only get incremental updates, but the repo size is just too big.

I see two main factors that make big:
- The build process, which runs in Travis CI, commits build output (test results and standalone.zip) to the gh-pages branches so they are publicly available, and these are big (the zip is 60MB each build).
- Selenium web driver binaries (and their older versions) included in the wiki.

I will try to find an alternative approach to publish build results so they don't increase the size of the repo (I hoped/expected these would only be retrieved when getting that branch, but they are always included in a normal clone).

After that is sorted I can do a cleanup of the repo, removing the no longer needed files, and push this to GitHub. To benefit from this everyone will need to do a new clone, and all pull request must be (re-) based on this updated version of the repo, or else the old content will just come back and increase the size again.

**Comment by tcnh** [comment]
For the time being, when you just want to clone the latest version, use the
depth parameter with git clone and set it tot a low number (i.e. 1). You
won't have the full history, but you do get a working copy.

Op 2 mei 2017 09:29 schreef "Fried Hoeben" <notifications@github.com>:

**Comment by fhoeben** [comment]
I believe I have updated the build process to no longer push the standalone.zip to gh-pages on each build. I also adjusted pointers in documentation (GitHub wiki, README, and HsacExamples wiki page in project) to point to the standalone.zip in the Maven SNAPSHOT repository of Sonatype.
This should stop the growth of repo with 60MB per build.

**Comment by fhoeben** [comment]
I believe the repo size is now 2.9 MB, better?

**Comment by keetron** [comment]
I think that is magical.
Now to update my fork 😄

**Comment by keetron** [comment]
Hmmm, how to make it so that my fork is small again?
There is a prune command I think?

**Comment by fhoeben** [comment]
I believe the easiest way is to delete your fork and make a new one...

**Comment by keetron** [comment]
It seems I will have to pick this up on my desktop as I get into issues when doing a fetch on my laptop. No idea why, it seems to be a network thing.

**Comment by fhoeben** [comment]
I'm not sure you can do a fetch from a previous clone of the repo. Do you also have problem when doing a clone on the laptop?

**Comment by keetron** [comment]
Also, I am confusing the plugin with the fixture. This one I made no changes on so I can remove mine and re-fork.

**Comment by keetron** [comment]
Cloning on the laptop of the trunk on the laptop is fine now.
