### ISSUE TITLE
Screenshot destination dir with different FitnesseRoot (-r command line arg)

### ISSUE THREAD

**Issue by andreptb** [fhoeben/hsac-fitnesse-fixtures#15]
Hi,

I'm using a different FitNesseRoot (-r command line arg) and it seems screenshot mechanism is not working properly. Probably because you're [using ContextConfigurator.DEFAULT_ROOT](https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/master/src/main/java/nl/hsac/fitnesse/fixture/Environment.java) to compose screenshot destination dir.

The same goes for URL generation, didn't test that but probably won't work if a different ContextRoot is configured in plugins.properties.

By inspecting FitNesse implementation I couldn't see an easy way to achieve that (get reference for configured FITNESSE_ROOT), since WikiPage or FitnesseContext objects that could provide this information aren't accessible by custom Fixtures or SlimTables.

**Comment by fhoeben** [comment]
I recall that I couldn't get the correct location, so went for the default.

In my code I do have a variable, that I use from jUnit runner, to control the location where screenshots are stored (`Environment.getInstance().setFitNesseRoot(outputDir)`). I assume you could set that (from a fixture) in your SuiteSetUp before you use storyboard. Can you give that a try?
If you have a generic solution that would improve the project I would be happy to receive a pull request. 

P.S. I've never had a need to change the root, can you explain how you use that?

**Comment by andreptb** [comment]
Working for a project with legacy code which shares the current working directory but have multiple FitnesseRoot. I arrived later so don't know the exact reason, but I guess the intention was to share the executable environment and easily switch FitnesseRoots.

About the generic solution I'm thinking to suggest a change in [FitNesse](https://github.com/unclebob/fitnesse) to allow this, maybe optionally injecting current page (WikiPage) in custom fixtures and slim tables. From there you could easily fetch [Global variables](http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.QuickReferenceGuide#GlobalVARIABLES)

**Comment by fhoeben** [comment]
Injecting into fixtures might be an issue for fixtures (since they live in a different, possibly non-Java, process. But the Slim tables should be able to get it. 
Is there a global variable for the root (I did not see it in the page)?

Can you write a fixture that allows `Environment.getInstance().setFitNesseRoot(outputDir)` to be called from the wiki and use that to set the correct directory?

**Comment by andreptb** [comment]
I can. It works. Unfortunatelly I must repeat the global variable for each FitNesseRoot. This just to make your fixture to work. We have other proprietary fixtures which shares the same problem, so I'm going for the generic solution. Thanks for the directions.

Closing the issue.

**Comment by andreptb** [comment]
https://github.com/unclebob/fitnesse/pull/755

**Comment by fhoeben** [comment]
The generic solution (unclebob/fitnesse#755) will not be sufficient to completely address this issue. This will give the custom table access to the test context. But the fixture will still not have the context, and it needs the directory to create the files. I can update the storyboard table to explicitly pass the information to the fixture, but this is still not ideal. This will not make it work when the Slim process is on a different machine, which is possible because then the fixture just can't write to the FitNesseRoot.

What would be needed really is an extension to the Slim protocol that allows fixtures to pass back files (relative path and content) to the FitNesse process (I'm thinking of some kind of object that can contain the 'normal' (as returned by a fixture today) result value and a list of files that belong with that result). The FitNesse process can then store the files in its filesystem on the correct location, and place the 'normal' result in the wiki result page.

**Comment by amolenaar** [comment]
I don't think the current Slim protocol is well suites for passing large amounts of data over the wire.
