### ISSUE TITLE
Use existing property for driver if exists

### ISSUE THREAD

**Issue by rjens** [fhoeben/hsac-fitnesse-fixtures#153]
In SeleniumDriverSetup in startDriverForWithProfile the property (webdriver.gecko.driver) for driver should not be overwritten if already set. For security reasons we are not allowed to run .exe files from outside "Program Files", and we get an error when using webdrivers/ in standalone version. We have the driver in PATH now, but can start with correct property if that is an easy solution.

**Comment by fhoeben** [comment]
Instead of using start driver with provided executables you can also just use the Java driver class (which will work if system properties are already set, there is also a method (`setPropertyValue()`)  to set properties) using SeleniumDriverSetup.
Please use: `start driver` with the required class name (and optionally a profile)
