### ISSUE TITLE
Ability to execute javascript ?

### ISSUE THREAD

**Issue by roydekleijn** [fhoeben/hsac-fitnesse-fixtures#154]
In some rare cases we want/need to execute some javascript.

Do you accept a pull request for that ?

**Comment by keetron** [comment]
Personally I would be really curious how you would solve the issue of running javascript inside a java runtime 😄

**Comment by roydekleijn** [comment]
I was talking about the browser test...

I like to do this:
```
    @WaitUntil(TimeoutPolicy.RETURN_NULL)
    public String runscript(final String script) {
        return getSeleniumHelper().executeJavascript(script).toString();
    }
```

for instance to change the behavior of an inputfield. (removing the datepicker)

**Comment by fhoeben** [comment]
In principle: I would accept a pull request, BUT I would always try to avoid using this myself in tests.
In the past when I was testing with a date picker I used two strategies:
 * select the date using the date picker
 * directly set the (hidden) input field underlying the picker (when the Javascript was too broken to be usable with Selenium).

The latter approach requires JavaScript (and I previous requests for a generic execute Javascript method were no longer needed when I mentioned the support for this), and browser test has a method to do this:`enterForHidden()`

When you do make a pull request I suggest you just make the method return 'Object' (so you can remove the `.toString()`) and add the method name to `NgBrowserTestBase.METHODS_NO_WAIT` (so that no waiting will be performed, and the `WaitUntil` annotation can be removed). 
Furthermore I would recommend naming the method 'executeScript', so this (technical) method is named like the Selenium function being called.

**Comment by roydekleijn** [comment]
Thanks for your advice.

The date fields of the application I'm testing are from the following format:
`
<input type="date" name="statdate">`

type=date doesn't work consistently chrome / firefox / internet explorer. In chrome you will see a native picker. But the client wants to execute the tests in all browsers.

I'll create a PR with your suggestions in mind:)

**Comment by fhoeben** [comment]
One additional question (just for my future reference): on stack overflow I see multiple answers suggesting that an input of type date can be filled with `sendKeys` and the date in the right format. That did not work for you, or not for all browsers?

**Comment by roydekleijn** [comment]
That doesn't work for chrome.. In chrome you will see a native kind of date picker

**Comment by fhoeben** [comment]
Merging via #155

**Comment by fhoeben** [comment]
Would it be a good idea to add (as a separate PR) a new BrowserTest command to select a date? The java method would set the attribute type (on the element found using browser test normal heuristic, passing it as arguments[0]), enter the value, and change the attribute back?

**Comment by fhoeben** [comment]
It turns out it is possible to enter value for input of type date via chrome: just use `enter <value> for <place>` instead of `enter <value> as <place>`. The 'for' version does not try to clear the input before setting the value, which was problematic.

**Comment by roydekleijn** [comment]
in regards of the date.... there is one downside of this `enter <value> for <place>` approach is that it doesn't take into account the system date-format settings.

**Comment by fhoeben** [comment]
You are absolutely right, so in your test case you have to know/take into account the OS configured notation for dates for the host that runs your browser. Based on how you determine the date to be entered a system property could be useful which allows you to configure formatting based on the machine that will host your browser.
There even is a Javascript function you can use which should get you a correctly formatted date, but for chrome headless has a bug (https://bugs.chromium.org/p/chromium/issues/detail?id=755338) which prevents that from working properly when using that browser.

All in all it seems much more trouble to work around it in that way than executing a simple script to get the job done. But I still feel the problem for selecting a value for such inputs should be addressed by a Java method that accepts a 'place' and a 'date value' and just sets the value (its implementation can find the element and execute the javascript to set the value), so that the implementation on how such a value can be set is not part of the wiki. 

I assume you have a script to achieve this (or do you only change the type using Javascript and then set the value using 'enter as')? Can you share that?

**Comment by fhoeben** [comment]
What do you think of changes in https://github.com/fhoeben/hsac-fitnesse-fixtures/tree/enterDateField?
