### ISSUE TITLE
Processing a large volume of data in Browser Test

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#165]
I am extending Browser Test to compare megabytes of text data (XML or JSON) from different URLs.

If I use "|$symbol=|value for|xpath=blah|" to hold the data for use in a later command, the huge retrieved text block prints on the FitNesse final report, making the test report long and potentially overwhelming the report generator.

Is there already a method available to stash the text returned from "value for|..." without printing it out, or is that something that would have to be added to the extension fixture as well?

**Comment by fhoeben** [comment]
At the moment there is no method available, custom code seems required (but is trivial of course :-))

If you want to store values (from Java code) from one test to the next (or from (suite)setup to tests) you could use the methods (`setGlobalValueTo()` and `globalValue()`). But I believe your use case just requires a Java local variable.

If your data is really huge you may need something like https://github.com/fge/largetext, instead of the Strings that are now used everywhere in the fixtures...


(P.S. when working with XML or JSON from URLs wouldn't XmlHttpTest or JsonHttpTest be more suitable than BrowserTest?)
