### ISSUE TITLE
Collapse long value of strings

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#166]
Is there a way to collapse or hide the values retrieved from expressions like these?
The text on a page can be very long, 
and distract from a test case checking only that the strings match.

| $saved-for-later= | value of | xpath=/xpath-expression | 
and 
| check | value of | xpath=/xparh-expression | $saved-for-later |

**Comment by fhoeben** [comment]
Not really (I once suggested that variables should be 'collapsable' but that never made it into the FitNesse's master.

The simplest solution is to contain the retrieval and check in a scenario, which remains collapsed if the check succeeds. But if that is not possible (for instance because the initial retrieve and later check require many steps in between) you can also pass the variable name and only retrieve the content in a scenario later. E.g.

```
|scenario|get value as _ |var|
| $@{var}= | value of | xpath=/xpath-expression |

|scenario|compare to saved _ |var|
| check | value of | xpath=/xparh-expression | $@{var} |

|script|browser test|
...
|get value as|saved-for-later|
...
|compare to saved|saved-for-later|
...
```

This is a bit of a hack, but it works like a charm....

**Comment by fhoeben** [comment]
My suggestion was in https://github.com/unclebob/fitnesse/issues/984
