### ISSUE TITLE
Is there any way to have HttpTest#request() include the whole request information (headers, query string, etc...)?

### ISSUE THREAD

**Issue by djlestephane** [fhoeben/hsac-fitnesse-fixtures#17]
The content of request headers can affect the response (I'm thinking about SOAPAction), so it would make sense to include request headers in the String returned by HttpTest.request(). This would enable people to troubleshoot header related problems in their tests.

**Comment by fhoeben** [comment]
I've not done this in the past because only the headers you explicitly set (i.e. 'set value <value> for header <name>') are sent. So the test shows the headers sent. Is there a specific reason the headers are not clear in your tests?

It would not be that hard to add, but I would think a separate method (e.g. 'request headers') which returns a Map would be better than adding it to request's return value.

**Comment by djlestephane** [comment]
Ok, if the test case only sends the headers that are explicitly set, then everything is clear, and you can disregard this issue.

Thanks
---
Stephane Mikaty


-----Original Message-----

Re: [hsac-fitnesse-fixtures] Is there any way to have HttpTest#request() include the whole request information (headers, query string, etc...)? (#17)
