### ISSUE TITLE
Use the fixtures stand alone

### ISSUE THREAD

**Issue by keetron** [fhoeben/hsac-fitnesse-fixtures#171]
Basically, is it possible / desirable to use the fixtures standalone in a java project without the FitNesse framework? It would save me the time of reinventing the wheel / get that sweet XML logfile content checks in my project.

**Comment by fhoeben** [comment]
I believe you can use most of it as-as. Especially everything in the `util` package.
The `fixture` package does have a dependency on FitNesse, but you can call them directly from another Java class also, if you are willing to have the fitnesse classes on your classpath you don't need to use them to call the fixture classes.

BUT some things will not be as easy to use I expect, for instance getting the formatted reponses received by 'http test' and its subclasses is HTML escaped and enclosed in `<pre>` tags, which I don't expect to be nice when called from Java.
When you want to use BrowserTest (and SeleniumSuiteSetup), that is also possible BUT you have to ensure you get your instances via `nl.hsac.fitnesse.slim.interaction.FixtureFactory` and not directly by just using `new` as the wait until logic will not work otherwise.
