### ISSUE TITLE
sendKeys partially fails, occasionally

### ISSUE THREAD

**Issue by lennyg1** [fhoeben/hsac-fitnesse-fixtures#183]
The |enter|something|as|some field| command uses sendKeys. On more than one type of application I keep running into the issue that sometimes it simply doesn't enter all the letters it should be entering. It appears that the element it supposed to be sending keys to gets focus too late, which results in missing keypresses. This means I miss digits/letters. It's not always the first digits that are missing, results vary by application tested.

It doesn't always happen and mostly occurs after running the same script a few times (using table template or scenarios).

Using the selenium type command works. So does using Javascript (execute script). Only the sendkeys fail.

One of the applications I test has validations on fields that trigger after keypresses. This could potentially be a cause, on this application the HSAC heuristics occasionally also miss a dropdown because the waitForEditable triggers too soon. The other application doesn't have anything like that happening, but still loses focus.

I have only been able to test with Chrome for now.

**Comment by fhoeben** [comment]
That's very strange. The only reason I can think of is indeed Javascript messing with the values being entered (removing focus of the field while Selenium is sending values, or an 'onkeypress' that prevents the value from appearing?).

Your idea that it might get focus 'too late' also suggests Javascript issues (maybe being triggered when leaving the field that previously had focus)? But to me that would only explain initial characters not missing, not others.

When you mention the 'selenium type command' what exactly do you mean? As far as I'm aware Selenium doesn't offer  a `type()` on elements. Do you mean BrowserTests `type()`? That method is actually also implemented using Selenium's `sendKeys()`.

Using Javascript to set the value bypasses all Javascript defined on the elements. So if that always works it indeed suggests the problems are being caused by Javascript on the page...

I don't know how I could help you further right now. If you can share a testcase I could reproduce or a pull request that fixes your issue I would gladly look at it further...

**Comment by tcnh** [comment]
Long shot, but I've seen some similar behaviou with slow validations in javascript frontends.

If it's validations on previous fields that could be stealing focus or changing the dom while sending keys, try using press tab after entering the previous input. That enforces any onblur events to fire, getting them out of the way before your next action.

**Comment by fhoeben** [comment]
The kind of problems @tcnh refers to are what prompted me to make 'richfaces test' (as subclass of browser test). Richfaces seems to have annoying javascript on *all* inputs that sometimes even cleared the content of other elements....

**Comment by lennyg1** [comment]
There is a selenium.type as far as I found in the selenium docs; https://seleniumhq.github.io/selenium/docs/api/dotnet/html/M_Selenium_ISelenium_Type.htm. I think in this case, selenium just does a bit of javascript to set value (like how you'd use execute script) and a click on //body when you use selenium.type().

However, the tab key @tcnh mentions really does seem to work (for now). I've made attempts at using a click or other commands, but that didn't always have the desired effect.

Would a feature where there would be an option in hsac-fitnesse-fixtures to supply a specific command (like a tab) to trigger automatically after specific commands? This way I don't have to fill my scripts with entering tabs. Perhaps it could even be extended to supply different Selenium commands; I know one of the applications I test I could simply add a waitforelementnotpresent for the javascript animation that triggers after something gets calculated in the background and that solves almost all issues. It also solves another thing I've come across, where using BrowserTest's 'value of', triggers too soon, and reading a value before it's finished calculating on a specific page. 

I can't supply a test case as the application works on an internal network, which means it's not accessible from the outside and it isn't a generic framework.

**Comment by tcnh** [comment]
In your case, you could for example extend BrowserTest and override the enterFor/As(In) methods to call their parent and perform pressTab afterwards.

**Comment by fhoeben** [comment]
The easiest fix is probably to override `sendValue(WebElement element, String value)`, similar to what[ I did for for RichFaces](https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/cd6ad73d38508e83f2dd10dc75e5d49454770cf6/src/main/java/nl/hsac/fitnesse/fixture/slim/web/RichFacesTest.java#L59). 
You could always press tab after entering a value, or only if certain conditions are true (if there is some way to 'detect' that element will trigger javascript).

If you just want to do it for all, create a subclass like:
```
public class TabAfterEnterTest extends BrowserTest<WebElement> {
    @Override
    protected void sendValue(WebElement element, String value) {
        pressTab();
    }
}
```
And update your wiki pages to do `|script|tab after enter test|` instead of `|script|browser test|`

**Comment by lennyg1** [comment]
At this moment I'll leave the tab in as a workaround. I am currently unable to load up an IDE and add a new class. Perhaps for the future it might be an idea to add a feature to HSAC fitnesse fixtures that adds this functionality (like implicit wait for angular, becoming an implicit wait for element/not wait for element or something, or adding a specific action after enter and select). This would be the approach I'm going for when I do get a chance to create a BrowserTest extension. Thanks for helping out!
