### ISSUE TITLE
Unable to find elements when 'search context' element is updated

### ISSUE THREAD

**Issue by fhoeben** [fhoeben/hsac-fitnesse-fixtures#185]
When during a BrowserTest script an explicit search context is set (using 'set search context to ...') and the element found for this context is later replaced (by Javascript) on the page BrowserTest will keep using the 'original' context element to its searches. All these searches will fail, as Selenium considers the context element 'stale' (i.e. no longer attached to page). 
In other words no 'place' will be found unitl a 'clear search context' is issued by the test.
No explicit error is added to the test report to highlight that places could not be resolved because the search container is 'stale', only generic timeouts stating the elements are not found are shown.

A workaround, if the point in the test the context is refreshed is known, is to do an explicit 'clear search context' and repeat (all) 'set search context ...' commands.

It would be better if BrowerTest kept track of the search contexts' established and would try to find them again if the current search context became stale. If the search context cannot be re-established an explicit exception should be shown in the test report to highlight WHY places could not be found.

**Comment by fhoeben** [comment]
Fixed in 3.14.1

**Comment by tcnh** [comment]
Since 3.14.1, I regularly see (in multiple projects):
`nl.hsac.fitnesse.fixture.util.selenium.StaleContextException: Search context is 'stale' and cannot be used to find elements. Context is: null`

This also happens in tests that do not explicitly alter the search context (by using ...in methods or set search context)
Never experienced this behaviour before.
