### ISSUE TITLE
XmlHttpTest fails when FitNesseRoot is not not located in default directory

### ISSUE THREAD

**Issue by MMatten** [fhoeben/hsac-fitnesse-fixtures#190]
I've noticed that when I have `FitNesseRoot` located at an alternate directory then my `XmlHttpTest` fails.

![image](https://user-images.githubusercontent.com/1895701/35725833-a61eb238-07fa-11e8-9bdd-07c7697ba4f0.png)

Are there some file dependencies involved somewhere here?

When `FitNesseRoot` is located in the working directory, from where I launch FitNesse, then my tests pass. Any ideas?

**Comment by fhoeben** [comment]
I know there are things in my fixtures that rely on the working directory being the parent of the `FitNesseRoot`. But I thought these were all related to the handling of http://files/... urls.

My guess is that the errors you see are caused by the fact that your `!path` statements use relative paths that rely on the other working directory.
