### ISSUE TITLE
Unable to check values with a carriage return

### ISSUE THREAD

**Issue by saskiav** [fhoeben/hsac-fitnesse-fixtures#192]
Hope you can help me out here:

I am having problems with checking the value of a radio button:

This is my code:

|script | browser test|
|check | value of | id=Geslacht0 |Man Vrouw|

and the result of the test:

![image](https://user-images.githubusercontent.com/35692851/36249448-05a0d50c-123b-11e8-835a-410a94d32b00.png)

How can I ignore the carriage return?

**Comment by AstridBleeker** [comment]
Have you tried:
|check|normalized value of|id=Geslacht0|Man Vrouw|
?

**Comment by fhoeben** [comment]
To ignore whitespace differences you can use `normalized value of` instead of `value of`.

Or you could make your expected value be (to include the newline, but then you still have to take care whether it is windows or unix newline:
```
!-Man
Vrouw-!
```

But don't you want to check the selected value instead of available options?

**Comment by saskiav** [comment]
Thanks for the help! 
I changed it into normalized and I got a good result now.
And yes, I want to check the selected value too.
