### ISSUE TITLE
Starting PhantomJS unnecessarily forces driver executable to be in project directory

### ISSUE THREAD

**Issue by JessefSpecialisterren** [fhoeben/hsac-fitnesse-fixtures#203]
When I try to start PhantomJS using `selenium driver setup`, I get the following exception:

```java.lang.Exception: java.lang.IllegalStateException: The driver executable does not exist: <project dir>\phantomjs-windows-%dbit.exe```

Even though phantomjs is in my PATH. Upon inspection, the following two lines https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/44b5e74cc9054c40515e0474cad904d7849b4eeb/src/main/java/nl/hsac/fitnesse/fixture/util/selenium/driverfactory/ProjectDriverFactoryFactory.java#L56-L57 seem to be responsible for this. Removing these two lines makes PhantomJS start as expected. This is because the system property value takes precedence over the PATH, even if the file specified in the system property value does not exist and phantomjs does exist in the PATH (see `PhantomJSDriverService.findPhantomJS`'s JavaDoc).

To solve this, I think just removing the mentioned lines should work. `phantomjsdriver` does not contain an executable and does not need one; just having phantomjs in the PATH is enough. It is like safaridriver in that regard, which also does not set a driverPath in `ProjectDriverFactoryFactory.java`. I'll submit a pull request that implements this.

**Comment by fhoeben** [comment]
You are right. Once upon a time the project bundled phantomjs and the path to executable was correct. 
There is an alternative approach IF phantomjs is on your path: just specify the java class name to start the driver (this can be done for any selenium driver): `|startDriver|org.openqa.selenium.phantomjs.PhantomJSDriver|`. 

That is actually what I would recommend in this scenario: no special handling by the fixtures is needed, so why ask for it?
The special method handling (without class names) is intended for when you want to use bundled selenium drivers, without the need to install addition software in the environment running the test. Which is not what your trying to do here.

So I would suggest either place the phantom executable at the correct location (for instance using webdriverextensions-maven-plugin), or just specify the class name.

On another note: why would you want to run tests with phantom (which is not actively being developed) instead of using chrome in headless mode? Chrome headless is much faster in my experience and more like the actual browser users will be using (I encountered a lot of edge cases with phantom which it did not support, many more than chrome headless). This is the reason the acceptance tests for the project are run with chrome headless these days (they used to be run with phantom in the past)

**Comment by JessefSpecialisterren** [comment]
> |startDriver|org.openqa.selenium.phantomjs.PhantomJSDriver|

Hm, that gives me `java.lang.IllegalArgumentException: No defaults known for: org.openqa.selenium.phantomjs.PhantomJSDriver`

> why would you want to run tests with phantom

I was working on a different pull request and wanted to test it with all supported browsers 🙂

**Comment by fhoeben** [comment]
Are you sure you did 'start driver' and not 'start driver for'? That message is from ProjectDriverFactoryFactory, which should not be called on 'start driver' (which uses LocalDriverFactory)

**Comment by JessefSpecialisterren** [comment]
> Are you sure you did 'start driver' and not 'start driver for'?

Gotcha, now it works, thanks! I guess we can leave the driverPath lines as they are then, and hope people running into the same problem as I did will find their way to this issue. Not that I expect many people to start using PhantomJS anymore 😇
