### ISSUE TITLE
Adding target="_blank" to thumbnails

### ISSUE THREAD

**Issue by boredland** [fhoeben/hsac-fitnesse-fixtures#214]
I think that adds some more usability, would it be okay, to do a PR?
https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/ad01177090d0d1d606778c2ae29e0bc4249da4e2/src/main/java/nl/hsac/fitnesse/fixture/slim/web/BrowserTest.java#L1866

**Comment by fhoeben** [comment]
And the result of download:
https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/ad01177090d0d1d606778c2ae29e0bc4249da4e2/src/main/java/nl/hsac/fitnesse/fixture/slim/SlimFixture.java#L326

But for that case we have to be sure that fixture methods accepting a file download still accept it with a target attribute, because it doesn't at the moment (the regex needs to accept more attributes/content on the 'a' element-open-tag instead of only 'href'):
https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/ad01177090d0d1d606778c2ae29e0bc4249da4e2/src/main/java/nl/hsac/fitnesse/fixture/util/HtmlCleaner.java#L15

**Comment by fhoeben** [comment]
I've added unit tests to the master branch (and updated the code) to ensure HtmlCleaner can deal with the extra content.
A PR adding `target="_blank"` is most welcome.

**Comment by fhoeben** [comment]
I was planning to make a new release tonight. I'l see whether I can add the target myself (or is your PR ready to go?).

**Comment by fhoeben** [comment]
Done in master

**Comment by boredland** [comment]
You have been to fast for me. Thank you very much though, will try it in a few hours!

**Comment by boredland** [comment]
Hi, will you push 3.25.0 to maven central?

**Comment by tcnh** [comment]
https://search.maven.org/#artifactdetails%7Cnl.hsac%7Chsac-fitnesse-fixtures%7C3.25.0%7Cjar
