### ISSUE TITLE
Can't check long dropdown list with available options for

### ISSUE THREAD

**Issue by Blackpander** [fhoeben/hsac-fitnesse-fixtures#219]
I always used the action | check | available options for | id=dropdownid | ${dropdownlist1} | which worked perfectly to check if al the options are available in a dropdown list. This action does work, but only with a short list. I tested a lot of scenario's and also in combination with variabeles.

If you put the output from | show | available options for | id=dropdownid | into a variabele with !define testvariabele {[ , option1, option2]} and put the variabele in the action like this: | check | available options for | id=dropdownid | ${testvariabele} |. This works with short lists, but if I use a long list with 100+ options the results shows the expected result in light red with nothing in dark red. That concludes that everything is the same, because there is nothing marked in dark red.

For this to get it working I tried this: | $test1= | available options for | id=dropdownid | and | check | available options for | id=dropdownid | $test1 |.

If I do this in the same script/run then the available options are dropped in the variabele test1 and then checked against variabele test1. This makes everything green.

Another check I did is: | $test1= | available options for | id=dropdownid | with | ensure | value | $test1 | equals | ${testvariabele} |. Another method of checking the options, but this also doesn't work for a long list, but shows green for a short list.

It looks like al these methodes work with short lists, but when used with a longer list, it also matches 100%, but show everything in light red with nothing in dark red.

I don't know if this is a bug or something I do wrong. I hope to hear from you :)

**Comment by fhoeben** [comment]
I haven't encountered this problem myself earlier so I can't say definitely what is causing this behaviour. But given your description it sounds like a problem in fitnesse itself, more precisely in how equality of lists is determined.
Let me elaborate: 'available options for' (at Java level) returns a list of strings, when you check this return value against a piece of text (a string) defined in the wiki (either directly in the cell or via a '!define'. The list-value returned is first converted to a single string and then compared to the value in wiki (so a string to string compare is done). But when you store the result in a variable the actual list is stored in that variable. When you later call the method again, with the variable as expected value, the returned list-value is compared against the variable directly (so a list to list compare is done).
This is all standard fitnesse behaviour, nothing to do with BrowserTest (I think).

If my assumption is correct the same problem should also be reproducible using ListFixture (when a long list is created by it, instead of by BrowserTest's available options for). 

If the problem is indeed caused by the mechanism I explained above I still cannot tell you why exactly the string/string compare is failing, sorry.

It's good to hear you found a workaround by means of a variable. Can you maybe create a sample wiki page showing this problem. Maybe that will help find a real solution.
