### ISSUE TITLE
Question: How FitNesse connect to SAP HANA

### ISSUE THREAD

**Issue by ybermejo** [fhoeben/hsac-fitnesse-fixtures#224]
Hi FitNesse Community,

Is there anyone that successfully connect FitNesse to SAP Hana database? I need your help on how do that thing. This is my first time doing this function so I don't have any idea. Thanks for kind consideration. :)

**Comment by fhoeben** [comment]
I don't have any experience using SAP Hana, but at what level would you want to connect? Do they offer some form of (http) API, do they offer a Java client, or is there a Java database connector (JDBC).

Using an http API will probably be possible using the fixtures in this library. [jdbcslim](https://github.com/six42/jdbcslim) or [dbfit](http://dbfit.github.io/dbfit/) might be of help if there is a JDBC connector available.

This project might not be the best place for this question. Maybe you can try [stack overflow](https://stackoverflow.com), and you may have to settle for writing your own FitNesse fixture to connect to the database using a Java library.

**Comment by fhoeben** [comment]
A quick google revealed that there indeed is a JDBC driver for sap hana: https://help.sap.com/viewer/0eec0d68141541d1b07893a39944924e/2.0.00/en-US/ff15928cf5594d78b841fbbe649f04b4.html

So to test at database level you can probably use one of the database libraries I mentioned above.

**Comment by ybermejo** [comment]
Hi @fhoeben,
Just checked the link you provide. After adding the ngdbc.jar in my classpath (class path is where my FitNesse saved right? e.g C://Downloads/FitNesse), I dont know how to load the driver as well as the succeeding steps. :(

**Comment by fhoeben** [comment]
I suggest you decide whether you want to use dbfit or jdbcslim (probably based on whether you prefer slim or fit tests, which may depend on other fixtures you like to use). And then check the documentation of that project (and maybe ask in their issues).

If your installation is based on my sample project the correct location to place the jar would be 'wiki/fixtures'. It would then be automatically available on the classpath. Ideally the jar needed is also available using maven, so you can have it placed there by maven instead of having to do a manual download.

I've used jdbcslim in the past in combination with my fixtures so that will work.

**Comment by ybermejo** [comment]
Hi @fhoeben 

Sorry to ask but you closed this issue?

**Comment by fhoeben** [comment]
I closed the issue because your question now has nothing to do with this project. Configuring jdbcslim is something that is documented by that project and any questions/issues regarding that should be placed with that project and not here.

You can add `jdbcslim.jar` next to `ngdbc.jar` (in `wiki/fixtures`) and do configuration in the wiki like described in https://rawgit.com/six42/jdbcslim/master/JdbcSlim.htm#JdbcSlim.UserGuide.3HowtoConfigureTheDatabaseConnection (this is quite hard to read, it might be easier to read by downloading https://raw.githubusercontent.com/six42/jdbcslim/master/JdbcSlim.htm and opening the local file with your browser)

**Comment by ybermejo** [comment]
Hi @fhoeben,
May I ask where to get the driver and not sure if what to put in the db url section? Is it the db host (e.g db.company.xx.xx:30015)?

**Comment by fhoeben** [comment]
according to the SAP site I linked above:
The driver is `ngdbc.jar`
its class name `com.sap.db.jdbc.Driver`
a connection url is something like `jdbc:sap://myServer:30015/?autocommit=false`, where you want to replace myServer with the db host (and maybe 30015 with a different port number)

**Comment by ybermejo** [comment]
I've run the test page to check whether it works but there's no response at all. Please see below my code. I'm not sure if there's a thing I need to add. 
![image](https://user-images.githubusercontent.com/40356873/43074494-0cb62878-8eb0-11e8-9ab1-1935eeb54d33.png)

**Comment by fhoeben** [comment]
I think you now have to add either a SQLCommand table, something like described at https://six42.github.io/fitnesse-blog/PlugIns.JdbcSlim.UserGuide.1ASimpleExample.html

Or, make a script table using SQLCommand, something like described at: https://six42.github.io/fitnesse-blog/PlugIns.JdbcSlim.UserGuide.7UsingSqlInScriptsAndScenarios.html

But again: these are questions to post at the jdbcslim project or stack overflow. NOT HERE...

**Comment by ybermejo** [comment]
Hi @fhoeben ,

Database connection is working already. Thanks for helping me out. Really appreciate it :)
