### ISSUE TITLE
Encoding parameter values

### ISSUE THREAD

**Issue by boredland** [fhoeben/hsac-fitnesse-fixtures#227]
Hi there! I'm using `setValueFor`:
|set value | PAULINA/ADELAJDA MS.50977b42cc3b | for | traveler|
|get from |https://url/endpoint|

However
|show | request |
returns 
https://url/endpoint?traveler=PAULINA%2FADELAJDA%2BMS.50977b42cc3b

Apparently set value encoded it. Which is nice. Sadly encoding produced `%2B` for the space. Instead it should have produced `+` in an urlencoded String:
https://www.w3schools.com/action_page2.php?text=PAULINA%2FADELAJDA+MS.50977b42cc3b

**Comment by fhoeben** [comment]
When I look at the git history I added that line when I added support to POST the current values.
https://github.com/fhoeben/hsac-fitnesse-fixtures/commit/0bc6d345b0391d9ddd16b86ffce600634d1a5827

**Comment by fhoeben** [comment]
So I'm guessing that space handling should (for some reason) be different between GET and POST.
I'm actually quite surprised by the `+` usage. I would actually expect a %20.

A quick google leads me to [stackoverflow](https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20#answer-1634293), which indeed suggest different handling of space between encoding for GET and POST.

Good catch.

Are you able to create a PR with unit or acceptance test that checks for the correct encoding in both cases and a fix to addresses it?
I'm happy to look at it myself, but I'm not sure yet when I'll get around to it.

**Comment by boredland** [comment]
I can try. For now I created a shabby workaround that Overrides urlEncode and replaces "%2B" with "%20".

**Comment by fhoeben** [comment]
Your workaround seems like it only works when you don't want to POST values... ;-)

**Comment by fhoeben** [comment]
Or when you don't want to use values which contain a '+'

**Comment by boredland** [comment]
Well: I currently don't. Either way: it's shabby. I'll work on it monday morning.

**Comment by fhoeben** [comment]
I did a bit more reading and what should happen:
- for GET query string a space should be encoded to '+', like you reported
- for POST a space should be encoded to '%20'

The helper method currently used by `HttpTest.urlEncode()` encodes for form posts according to its Javadoc, so this means it will produce '%20'. This is no good for creating a query string. `JsonHttpTest.urlEncode()` overrides the superclass method (in a bad way; if anything it could have replaced '%20' in the superclass' result by '+' instead of doing something before the superclass is called), but it shouldn't.

The behaviour should be corrected in HttpTest, and JsonHttpTest can just use it.

**Comment by fhoeben** [comment]
Correction: the current HttpTest.urlEncode() does produce a '+', and officially a GET should use '+', so I got it the wrong way around in my previous comment. Would sending a '%20' in the URL also work for your request (as opposed to the the '+' you indicated in the original issue report?)

**Comment by fhoeben** [comment]
I've merged that branch into master.
Please let me know whether this fix addresses your issue, or additional changes are required.

**Comment by boredland** [comment]
Works like a charm. Thank you so much!
