### ISSUE TITLE
Non-globally trusted certificates not working with chromedriver 79+

### ISSUE THREAD

**Issue by timovd** [fhoeben/hsac-fitnesse-fixtures#292]
The PR https://github.com/web-platform-tests/wpt/pull/19377 is merged into chromedriver 79.x (79.0.3945.36), so it's not possible to start a test script when your SUT has no valid certificate without manually accepting the certificate risk. The workaround is to explicitly ignore these errors; start Chrome with argument --ignore-certificate-errors.

**Comment by fhoeben** [comment]
Chromedriver 79.x is included in hsac-fixtures 4.8.2 so this issue might pop up once upgrading to that version, or higher.

**Comment by fhoeben** [comment]
@timovd am I right in assuming passing the `--ignore-certificate-errors` can be done using the wiki code below (in a SuiteSetUp page)?

```
|script         |map fixture                            |
|set value      |--ignore-certificate-errors|for|args[0]|
|$chromeProfile=|copy map                               |


|script          |selenium driver setup             |
|start driver for|chrome|with profile|$chromeProfile|
```

**Comment by timovd** [comment]
Adding this argument will ignore the certificate error indeed.

**Comment by fhoeben** [comment]
When your chrome is remote (i.e. selenium grid) you can pass the argument via the capabilities. 

For instance for a test run on a build server by passing `-DseleniumJsonCapabilities={'browserName':'chrome','chromeOptions':{'args':['--ignore-certificate-errors']}}`

When using the docker images with chrome one can pass this option by updating the `FITNESSE_OPTS` environment variable. Instead of setting `seleniumBrowser` one should set `seleniumJsonCapabilities`. The full environment variable becomes something like: `-Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true -DseleniumJsonCapabilities={'browserName':'chrome','chromeOptions':{'args':['--ignore-certificate-errors']}} -DseleniumGridUrl=http://localhost:4444/wd/hub`
