### ISSUE TITLE
Unable to select empty option on dropdown menus

### ISSUE THREAD

**Issue by Eddie1802** [fhoeben/hsac-fitnesse-fixtures#296]
After a recent update it is no longer possible to select an empty value from a dropdown menu.

This is probably introduced by commit:
https://github.com/fhoeben/hsac-fitnesse-fixtures/commit/8c96555f91f38e1c2f0def3574b3f32bdc2e7957

Consider the following test:
[testEmptySelectOption.txt](https://github.com/fhoeben/hsac-fitnesse-fixtures/files/4072456/testEmptySelectOption.txt)

In the steps where you leave the option empty, the first not empty option is selected. In this case '2'.
Expected is that the empty option is selected.

![image](https://user-images.githubusercontent.com/2613395/72542662-caf34300-3884-11ea-9ea6-f77b71297142.png)

**Comment by fhoeben** [comment]
I don't believe this to be because of that change. The problem seems to be in the selector used to find the option. We search for an element with an empty text(), but the browser says there is no such element (as it thinks the option has no text(), which is not the same as an empty one).

If this worked in the past it probably broke because of change in browser's handling of options without text, or longer ago when we switched from the extremely slow Selenium standard helper to our own option handler using xPaths.

**Comment by Eddie1802** [comment]
For people looking to select empty options from a dropdown, I've now applied the following workaround which uses selectByVisibleText in the selenium Select class in our BrowserTest subclass.

    @Override
    protected boolean clickSelectOption(WebElement element, String optionValue) {

       // Select the option without text.
        if (element != null && optionValue.equals(""))  {
            Select dropdown = new Select(element);
            dropdown.selectByVisibleText(optionValue);
            return true;
        }

        return super.clickSelectOption(element, optionValue);
    }

**Comment by fhoeben** [comment]
@Eddie1802 does the new release (4.10.0) indeed remove the need for the workaround?

**Comment by Eddie1802** [comment]
Yes, I've tested it today, works fine. Thanks for the quick fix.
