### ISSUE TITLE
BUG: seconds before timeout reseting to 10s

### ISSUE THREAD

**Issue by teunisv** [fhoeben/hsac-fitnesse-fixtures#313]
```
|script                |browser test             |
|seconds before timeout|60                       |
|check                 |seconds before timeout|60|
|start                 |browser test             |
|check                 |seconds before timeout|60|
|start                 |timer fixture            |
|start                 |browser test             |
|check                 |seconds before timeout|60|
```
In my opinion this should all be green, but last 2 return 10 instead of 60

**Comment by fhoeben** [comment]
this is not a bug. each instance of browser test gets its own 'seconds before timeout'. This ensures that each test/script table starts in a reproducible state and does not keep settings from previous tests.

If you want the standard timeout with which tests start to change (e.g. be 60s instead of 10s, sounds like WAY to long BTW), you have some options:
- create a single instance of bowser test (for instance in your SuiteSetUp) set its timeout and reuse this in all your tests (using 'pop fixture' and 'push fixture' to retrieve/store if you need to use other fixtures)
- create a scenario that starts browser test instead of doing that in a script table, you can then omit the 'browser test' cell from your script tables and call the scenario in the first row
- pass the desired timeout as a constructor parameter and use a wiki variable to have the actual value, so you get something like`|script|browser test|${DEFAULT_TIMEOUT}|`,  
- change the default timeout setting (for a CI run) this can be done via a system property: `seleniumDefaultTimeout`, see https://github.com/fhoeben/hsac-fitnesse-fixtures/wiki/3.1.-Build-Server-Selenium-Configuration 

But really: how horrible is the system you're testing if the default timeout of 10s is not sufficient. I hope you are planning to use another default to make it shorter, not longer.

**Comment by teunisv** [comment]
for reference: http://fitnesse.org/FitNesse.SuiteAcceptanceTests.SuiteSlimTests.ChainWithInstanceTest
