### ISSUE TITLE
Variables passing bug

### ISSUE THREAD

**Issue by Taxanas** [fhoeben/hsac-fitnesse-fixtures#324]
Hello, @fhoeben , 

Looks like there is a bug, that you cant access variables created in **SuiteSetUp's** and other test pages by 'EchoFixture' in 'JsonFixture' for validation values.
Attaching screenshot:

### Variable created in SuiteSetUp
![image](https://user-images.githubusercontent.com/57341655/83485523-e9627f80-a4af-11ea-9962-a22e3176a5b7.png)

### Variable created in previous test page:
![image](https://user-images.githubusercontent.com/57341655/83486764-80c8d200-a4b2-11ea-8145-1c41772cb8c8.png)

Additional information:

1. Variables are not accessible **only** for validation values (as shown in screenshot).
2. Variables are accessible if they are created  in **SetUp**, or same test page. 
3. HsacFixtures version 4.15.2
4. Fitnesse version 20200501

Workaround:
Call vars by EchoFixture on same test page, and recreate them.. :)
`|script|echo fixture|
|$variable=|echo|$variable|`

Please don't hesitate and ask if anything more is required,
Julius

**Comment by fhoeben** [comment]
Hi @Taxanas thanks for reporting this. 
I never ran into this problem before, but with your explanation I do believe I know what is going on. 

The variable is created in the Slim server (i.e. the Java process running JsonFixture) and keeps its state there, but the wiki does not keep its variables between SuiteSetUp and test pages (or test pages in the same run). Variable usage (i.e. passing it **to** echo fixture or json fixture) is done in the Slim server, but checking the value in a script is done in the wiki. Therefore passing the variable into the fixture works, but checking against it doesn't.

Is it correct that you don't even need to use json fixture to show the problem? I believe the same issue would be shown if the MyTest page contained:
```
|script|echo fixture|
|check|echo|$variable|$variable|
``` 

Is that correct?

If this is indeed the case please close this issue and report it as a FitNesse issue at https://github.com/unclebob/fitnesse/issues

From a conceptual point of view you exposed a weakness in FitNesse's handling of variables: their scoping. The wiki uses a different concept of scoping than Slim (I'm not sure what the situation is for Fit). 
Because while it makes sense that a variable assigned during SuiteSetUp would be accessible to tests in its suite, I would very much like that variables would be cleared after each individual test (and variables assigned in SuiteSetUp after the suite). I've run in to trouble because a previous test assigned a variable that another test assumed would be empty initially.

Fixing this will not be easy. I don't believe it is possible while maintaining backward compatibility.

So for now your workaround is probably the best approach for your tests: using echo fixture (or string fixture) to bring the variable's value from the Slim server into the wiki's page context if you need it there.
An alternative you could try is whether using the JavaScript expressions, introduced some versions back, make the workaround a bit smaller on your test pages. What happens when you put the following content (note the backpacks around the last `$variable`) in the MyTest page?
```
|script|json fixture|
|load|{"variable": "$variable"}|
|check|json path|variable|`$variable`|
```

**Comment by tcnh** [comment]
I've once tried to start fixing this, but it requires changes to the slim protocol. That;s where I decided it was not worth the hassle.
When we really need variable values from suiteSetUp in a test, we just use the workaround (the backtick expressions will also work, if you use ``` $`variable` ``` (note the backtick starting after the $).
In most cases though, it's also possible to move some variable setting to setup or a collapsed include in a test template.

A nice 'feature' resluting from this anomaly is that it can be used to hide sensitive information from test reports. I have a habit of setting stuff like credential information from suiteSetup, so that they don't show up in the HTML reports

**Comment by Taxanas** [comment]
@fhoeben , you are correct. EchoFixture itself cannot reach var for checking against. Will close the issue as its not the scope of this project .

@tcnh , thanks for insights. Sadly, i cannot move variables creation to SetUp's as those variables are dynamically generated and used by multiple test pages (SetUps would overwrite).

Suggested workaround doesn't work for me:
![image](https://user-images.githubusercontent.com/57341655/83497634-6e0ac900-a4c3-11ea-91cd-f73d9b698095.png)

Maybe more hints are available? :)

**Comment by tcnh** [comment]
doing  wiki check will not work (as it resides on the wiki side) until you have explicitly set the value to the var again. Example:

![image](https://user-images.githubusercontent.com/2232710/83500935-b58f5600-a4bf-11ea-9dee-b0f3333f8073.png)

What does work, is using the value of the symbol as an argument to a fixture (as you see when passing it to string fixture's vaklue of method).

What is your use case? If it's just validating a value that was set in SuiteSetUp, the easiest way to do so is in SuiteSetUp itself?

**Comment by Taxanas** [comment]
Understood. 👍 Will get used to it.
Still looks like a bug, as same vars are reachable, when creating them in SetUps :D 

My case is creating multiple "Parents", which have multiple "Sons". Then feeding data from multiple "Sons" by different protocols TCP/UDP/MQTT in parallel being connected via multiple StreamSSE (each by different authorizations by "Fathers"), collecting data, and validating later, that correct "Fathers" got correct Stream Data ;)
Using Fitnesse for the visual clarity of "after execution" what is wrong/right :)

**Comment by tcnh** [comment]
I agree it looks like a bug (and probably is). The reason is that a setup is executed as part of a test case, whereas suite setup is executed as a separate test case. One could argue that bleeding symbol values from one test to another is unexpected as well.
