### ISSUE TITLE
Headless Test Execution

### ISSUE THREAD

**Issue by mvfsp14** [fhoeben/hsac-fitnesse-fixtures#348]
Hi @fhoeben, 

Good day and I hope you're well and safe. 

I just wanted to ask your expertise regarding headless test execution using FitNesse - Browser Test.

I'm new with this headless execution as originally we are using SauceLabs to run cross browser testing. And we have this requirement to make our web automation packs flexible/configurable that we have the option to run it: 

- via SauceLabs (Done / Completed)
- Local Machine - Actual Browser execution (Done / Completed)
**- Headless for both Local Machine & DevOps pipeline** 

Since I started checking this function this morning, I come up with a few of questions about it: 

### 1. What's the correct script on how to headless execute for Mozilla Firefox, Safari, Microsoft Edge and Internet Explorer? As of now, I can only run it in Chrome using this script: 

`|script                 |map fixture                  |
|set value              |headless         |for|args[0]|
|set value              |disable-gpu      |for|args[1]|
|set value              |--start-maximized|for|args[2]|
|$chromeHeadlessProfile=|copy map                     |

|script          |selenium driver setup                     |
|start driver for|chrome|with profile|$chromeHeadlessProfile|`

I tried changing the chrome to "firefox", "safari" and other for IE and Edge, but what happened is that the actual browser is opening on my local machine and not "headless" like what happened on Chrome. 

![image](https://user-images.githubusercontent.com/54445608/94904639-31c99280-04ce-11eb-988c-db7f8c064cb4.png)

### 2. I'm not sure if I miss something, but is there a way to make the the screen size and quality of screenshots same when I run it on Local Machine / SauceLabs? When I run it in headless (using the configuration from my #1 question, it looks like the screen is not maximizing even I have **"set browser size to maximum"** command in BrowserTest. Here's the comparison using the same test script: 

Headless Chrome: 
![image](https://user-images.githubusercontent.com/54445608/94906739-989c7b00-04d1-11eb-91d5-425bb691e11e.png)

Local Machine - Actual Browser & SauceLabs: 
![image](https://user-images.githubusercontent.com/54445608/94906824-b79b0d00-04d1-11eb-9eea-46ba24564641.png)

Based on the 2 images above, quality of image in my headless run in Chrome is very different with the screenshot generated when running it on Actual Browser and SauceLabs.

### 3. Also, since our project uses Jenkins to trigger our web automation packs going to SauceLabs, do we have something that needs to be setup to Jenkins in case we wanted to run our FitNesse web automation packs by only using Jenkins? Or just to make sure that the we have the latest webdrivers? Because right now, here's the list of webdrivers that I have when I extracted the latest standalone package: 
![image](https://user-images.githubusercontent.com/54445608/94910688-a48b3b80-04d7-11eb-8f2a-7efcfecf2b6d.png)

I'm not sure if I'm missing something here.

### 4. Is this something that we can replace SauceLabs moving forward? Since we knew that SauceLabs is kinda pricey and slowness to complete test is still there. Does headless supports cross browser and parallel testing? 

Thank you!

**Comment by fhoeben** [comment]
@mvfsp14 a lot of questions :-)
Headless testing is quite a broad topic and I don't know whether a GitHub issue is a good way to answer them. I'm not very experienced using headless testing. My experience is limited to headless testing using Chrome and PhantomJs before that.

1. How you start a headless version of a browser is browser specific, there is no generic approach that works for all browsers. I expect the new Edge will be very similar to Chrome, but Safari and Firefox might not support headless runs. I know IE does not support it.

2. You can specify the screen size for headless browser (as there is no real screen to define the size). I believe you can add an argument like `window-size=1920,1080` to set what the screen size should be.

3. If you want to run tests (headless) locally on the Jenkins server you will need the WebDriver for the platform the Jenkins runner (are they still called slaves) is on. If that is Linux you need different web drivers then included in the standalone.zip. The drivers need to match the OS and browser version you plan to use (e.g. download it and change its name to chromedriver-linux-64bit, and make sure its executable). You can also place them at another location, but that requires extra setup/configuration.

4. I would suggest to limit headless testing to pure functional tests on one browser. I find that there sometimes are subtle differences between chrome headless and normal on the same platform. So I would not recommend it for cross platform and browser test.
To run tests in build pipeline I prefer to use docker containers containing a browser. This keeps them nice and isolated and does not require a specific headless mode. But this is limited (in my experience) to Linux. I believe the Selenium project publishes docker images (standalone I believe they call them) for Chrome and Firefox. I create my own version of the chrome image, to which I add FitNesse and my fixtures and publish those and use them for my own tests. What I also like about this approach that you can easily scale up to more machines and get a fixed combination of OS, WebDriver and browser version (no issues with auto updating chrome). 
You can also setup a local Selenium grid to run your cross platform tests. I have done that in the past: a Mac mini and virtual Windows machine on VM ware, or an unused desktop all work. But this require initial setup, maintenance and occasional troubleshooting.
There are other cloud providers such as BrowserStack, but I have no personal experience with those.

**Comment by Mohim-Singla** [comment]
Hey @mvfsp14 and @fhoeben I also intend to run some tests with chrome browser in headless mode. But the issue is the browser hangs upon loading the webpage and returning the following error: [SEVERE] Timed out receiving message from renderer.
Upon finding a solution to this error I realized that it might get resolved by setting the PageLoadStrategy to NONE or EAGER. I'm new to fitnesse and I'm unable to pass this argument to the chrome profile, Could you please help me with the correct syntax/fitnesse table as to how can I set the value of PageLoadStrategy to NONE.

Here is my code: 
|script |map fixture |
|set value |headless |for|args[0] |
|set value |disable-gpu |for|args[1] |
|set value |--start-maximized |for|args[2] |
|set value |--no-sandbox |for|args[3] |
|set value |--disable-dev-shm-usage |for|args[4] |
|set value |--dns-prefetch-disable |for|args[5] |
|set value |--silentOutput=true |for|args[6] |
|set value |  !-PageLoadStrategy.NONE-!  |for|  !-setPageLoadStrategy-!  |  
|$HeadlessProfile=|copy map |

|script |selenium driver setup |
|start driver for|chrome|with profile|$HeadlessProfile|

Here is the error code:
[12:25 PM] Mohim Singla

__EXCEPTION__:ABORT_SLIM_TEST:nl.hsac.fitnesse.fixture.slim.StopTestException: Could not start a new session. Response code 400. Message: invalid argument: entry 0 of 'firstMatch' is invalid from invalid argument: cannot parse capability: goog:chromeOptions from invalid argument: unrecognized chrome option: capabilities
