### ISSUE TITLE
Upgraded to 4.5.4 \ 20190628, issue with test case run ordering

### ISSUE THREAD

**Issue by bl185052** [fhoeben/hsac-fitnesse-fixtures#368]
We have been running an old build of hsac-fitnesse for a while. I decided to upgrade to the latest, then back down versions until I noticed that my fit tests were no longer starting before my slim tests. They used to just run alphabetical inside the suite, but now it has grouped all of the dbfit cases together and the slim together, and then run dbfit first.
ALL_UNCLE_SUITE_SETUPS as true or false doesnt seem to make a difference.

**Comment by fhoeben** [comment]
DbFit tests use the 'fit' test system, correct? As far as I'm aware FitNesse has always run al fit tests first before running any slim tests. If something changed there I expect that to be a FitNesse change and not a hsac issue.  

I'm not a 100% what the situation is you describe (your statement of upgrading and then 'back down versions until' confuses me, sorry): what version of FitNesse and hsac-fitnesse-fixtures are you using when you see all tests run alphabetical (i.e. slim and fit tests intermixed)?

Could it be that when you observe that all tests are executed alphabetically all tests are run by the same test system (i.e. either only slim of fit tests are run)? Or that the visualisation of test ordering somehow changed between versions, did you see the alphabetical order in the browser while the test run, or in a jUnit report, or ...?


Aside: `ALL_UNCLE_SUITE_SETUPS` should only influence when (and how often) SuiteSetUp and SuiteTearDown are run, so indeed not the ordering across test systems.
Even when using 'suite partitioning' I expect each partition to first run any fit tests in it and then its slim tests.

**Comment by bl185052** [comment]
Yes DbFit uses fit. Our system was running whichever build you have v20190224 in. So then I upgraded to the latest 4.23.1 and noticed the ordering change. Eventually I found that the change to ordering was made in 4.5.4, which looks like fitnesse v20190628. 
Basically we have multiple test suites. Each suite needs to run about 500 web service calls, and then about 10 sql server tests to verify that the web service calls did their job. Long ago, i noticed that the cases inside the suites ran alphabetically. So we just numbered the cases, putting SQL down at the bottom, and that worked perfectly. So, the slim WS calls ran first, then DBfit at the bottom. But now its reversed, and no matter what the name of the test case is, all of the fit cases run first. The only reason I can think is that "Fit" comes before "Slim". Even if I run multiple suites at the same time, it runs all of the fit tests in the suites first and then slim.

**Comment by fhoeben** [comment]
I had not expected this. Any chance the ordering was not fully alphabetical, but it was: slim first and then all fit tests (which suited your purposes ;-)), and within each test system the tests were ordered alphabetically?

Anyway addressing this ordering does not seem an easy change. For now I see a couple of fixes (or workarounds if you prefer):
- add a tag to to all database tests and run each suite in two phases: first run all tests without the tag, and then all tests with the tag
- (more work, but maybe easier/cleaner in the end) use another database fixture that runs in slim (I've used [jdbc-slim](https://github.com/six42/jdbcslim) in the past so I could interleave database actions with test steps on services and browsers)
- (or the other way around) find a service fixture that works in fit

My personal preference would be to use a single test runner so that database checks could be done in the same test case as service/browser tests (instead of having a suite where later tests depend on earlier tests, I expect this also limits your ability to (re)run a subset of tests from a single suite easily). But I don't know your exact situation of course.

**Comment by bl185052** [comment]
I put the older build back on the machine, and moved 1 of the dbfit tests to the top. So for example, from top to bottom is:
fit
slim
slim
slim
fit
fit
Now it runs all the fit first, and then slim. If I move the first fit back down below slim, it runs slim first. So my thinking is in the old build, first it orders alphabetically, and then by type. And now in the new build, they just older by type. 
There are some nice features in the newer builds I like, so I think Ill give jdbc-slim a try. There isnt much activity lately at dbfit anyway, so it may be abandoned by now.

**Comment by bl185052** [comment]
Can you by chance provide an example for adding a tag to the tests? In case I cant figure jdbc slim out. It seems like there's a lot to it.

**Comment by fhoeben** [comment]
See http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.WritingAcceptanceTests.TestSuites.TagsAndFilters 
You add them via the 'Properties' menu option of a suite (or test).

Setting up for using jdbc-slim was not really easy as I recall correctly. But once that was done it was pretty smooth sailing.
I used jdbc-slim mostly from scripts and scenarios, so I could integrate/intermix easily with hsac-fixture calls. See https://six42.github.io/fitnesse-blog/PlugIns.JdbcSlim.UserGuide.7UsingSqlInScriptsAndScenarios.html

**Comment by bl185052** [comment]
Awesome thanks for the help
