### ISSUE TITLE
[Question] How do I get JUnit testresults via command line?

### ISSUE THREAD

**Issue by Fastest-Turtle** [fhoeben/hsac-fitnesse-fixtures#389]
Related to [#1340](https://github.com/unclebob/fitnesse/issues/1340)

## Have you looked at possible resources for answers? 
**Yes**

## If your answer isn't out there, please describe your question
I'm looking for any solution into creating testresults in JUnit from the downloaded HSAC FitNesse fixtures. 

All available commandline options from the [Restful Services](http://fitnesse.org/FitNesse.UserGuide.AdministeringFitNesse.RestfulServices) have failed so far. 

`java -jar fitnesse-standalone.jar -c "HsacExamples.SlimTests.BrowserTests.Angular2CalculatorTest?test&format=junit"`

I would like to create test result files that are automatically accepted by Azure DevOps, without using Maven.

**Comment by fhoeben** [comment]
I suppose the `fixtures` directory is directly below where you issued the command previously.

Maybe the command needs to change to (because you are on Windows):
```
java -cp "fixtures;fixtures/*" -DfitnesseSuiteToRun=FrontPage.TestautomationDemo.SearchEngineTest nl.hsac.fitnesse.junit.JUnitConsoleRunner nl.hsac.fitnesse.HsacFitNesseSuiteStarter
```

**Comment by fhoeben** [comment]
You need to add jUnit 4 and its dependencies to the fixtures directories :-(
Very annoying setting this up without Maven, because who want to manually find the dependencies of another library.

Does it have to work like this? Can't you use the docker containers (where I fixed all this)?

If you really can't use the docker container at runtime maybe you can use it as an install tool: create a container and copy the contents of its `/fitnesse` directory to your local machine. Add your tests (and Java classes/jars if any) to this directory's `/wiki` (and `/fixtures`) and then run this command...

**Comment by fhoeben** [comment]
Any progress?
