### ISSUE TITLE
fix tag to match release

### ISSUE THREAD

**Issue by hboutemy** [fhoeben/hsac-fitnesse-fixtures#406]
until 5.0.0, git tag represented the release as expected: https://github.com/fhoeben/hsac-fitnesse-fixtures/commit/5a58a6342103a27fb380e340dffcc9384c4eab41

since 5.1.0, git tag points to a SNAPSHOT: https://github.com/fhoeben/hsac-fitnesse-fixtures/commit/63a8997fb9322116ad8f0e588abdfb419529411f

the tag does not correspond to the binary release

**Comment by fhoeben** [comment]
@hboutemy you are right, this is caused by the new release process via GitHub action. The change in the `pom.xml` is not pushed to the repository before the release (and tag) are made.
This is the only difference, I believe. The code is completely identical so for my purposes the tag is 'good enough'.

But we could do better. Do you feel you could create a PR to update the GitHub action to add a step that does a push after the code is uploaded to maven central and before the GitHub release is made? (Similar to the push done after the version number is updated after the release)

**Comment by fhoeben** [comment]
@hboutemy  5.2.1 and 5.2.2 should both have tags matching the binary release. Is that indeed the case?

**Comment by hboutemy** [comment]
5.2.4 is now fully ok https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/nl/hsac/hsac-fitnesse-fixtures/README.md
great job done :)
