### ISSUE TITLE
Req: Ability to get value of specified attribute inside a element

### ISSUE THREAD

**Issue by teunisnl** [fhoeben/hsac-fitnesse-fixtures#41]
Im trying to acces contens of specified attribute in a element
Tried `value of|xpath=(.//input[@value="" and contains(@name,"pcnr")])[1]/@name`
but this always return null (xpath is correct)
`value of|xpath=(.//input[@value="" and contains(@name,"pcnr")])[1]` works and returns a empty string as expected

**Comment by fhoeben** [comment]
This is expected behavior. The fixture is aimed at testing web pages at a functional level, attributes of elements are not something which is shown by the browser and therefore are also not accessible. Why would you want to test something no human using the page sees?

The ability to specify an xPath is targeted to find elements, not to evaluate random xPath expressions.

So the first 'value of' returns null as no element is found using that xPath (as it selects an attribute and not an element). The second does work, as it selects an element, but returns the value attribute of that input, and not its name attribute.
