### ISSUE TITLE
Version compatibility issue with hsac-fitnesse-plugin

### ISSUE THREAD

**Issue by aquddos123** [fhoeben/hsac-fitnesse-fixtures#411]
I have old test test system configured using maven, maven-classpath-plugin, and maven-antrun-plugin. I am using latest version of FitNesse 20220319 and Selenium 3.14.0. 

Recently, I tried integrating HSAC's fitnesse plugin and HSAC's fixtures and it went well. I've added hsac-fitnesse-fixtures as dependency to POM.xml and downloaded hsac plugin JAR from https://github.com/fhoeben/hsac-fitnesse-plugin/releases into /wiki/plugins/ directory.  This is only working fine with hsac-fitnesse-fixtures 4.x.x and when I switch to version 5.x.x, all script tables start erroring out with "The instance scriptTableActor.setValueFor. does not exist". 

I've tried hsac-fitnesse-plugin versions 1.32.2, 1.32.9, 1.27 with hsac-fitnesse-fixtures 5.x.x but no luck. I've verified fixture locations and imports correct. Any idea?

**Comment by fhoeben** [comment]
Are you still using selenium 3.14.0 with the fixtures 5.x? I believe that might be the cause of your issues. Starting from 5.0.0 the hsac-fixtures use Selenium 4.1.2

The error you report is a bit vague but reminds me of situations where I had issues with script tables not being able to instantiate a class. That could easily be caused by Selenium 3 vs 4 problems.

Can you give some more details on what the (suite)setup and test page that give you this error look like. And what exactly the error looks like (which error on which row). Also the "Execution Log" (available from the button top left of screen after a run) might provide some useful details

**Comment by aquddos123** [comment]
@fhoeben thanks for the quick response. 
The selenium and fitnesse versions I mentioned above are from my existing project and all existing tests (based on Decision tables with custom fixtures) are running fine. I believe that has nothing to with the hsac plugin integration. 

Currently, after integrating hsac plugin/fixtures with my existing project, I am running one of the sample tests from hsac fixtures lets say `HsacExamples.SlimTests.BrowserTests.ScenarioTest`. It should be using default SuiteSetUp given under HsacExamples and FitNesse and Selenium versions packaged with `hsac-fitnesse-fixtures-5.2.4.jar`, No?
Import tables are working fine BUT all Script tables are not. Every action/row is yellow highlighted with the following errore

Top Row: java.lang.NoClassDefFoundError: Could not initialize class nl.hsac.fitnesse.fixture.Environment
All other rows are like:
The instance scriptTableActor.secondsBeforeTimeout. does not exist
The instance scriptTableActor.open. does not exist
The instance scriptTableActor.clickIfAvailable. does not exist   
The instance scriptTableActor.clickIfAvailable. does not exist
The instance scriptTableActor.enterAs. does not exist
The instance scriptTableActor.press. does not exist

Unfortunately I can't attach screenshot here. Execution Log is also empty. See below the copy of one Script table from page source. 

`<html><body>
<br>First we go to the Discography page for Van Morrison.<br><br>

script | browser test java.lang.NoClassDefFoundError: Could not initialize class nl.hsac.fitnesse.fixture.Environment
-- | --
seconds before timeout The instance scriptTableActor.secondsBeforeTimeout. does not exist | 60
open The instance scriptTableActor.open. does not exist | https://www.allmusic.com
show The instance scriptTableActor.clickIfAvailable. does not exist | click if available | AGREE
show The instance scriptTableActor.clickIfAvailable. does not exist | click if available | id=exco_sticky-x-button
enter The instance scriptTableActor.enterAs. does not exist | Van Morrison | as | Search
press The instance scriptTableActor.press. does not exist | enter
click The instance scriptTableActor.click. does not exist | Van Morrison
click The instance scriptTableActor.click. does not exist | Discography


<br>Then we check some entries.<br>
</body>
</html>`

As mentioned earlier, the same test start working fine if I switch hsac-fitnesse-fixtures back to 4.x.x
Does this help of you need more info? Please let me know.

**Comment by fhoeben** [comment]
From you exception I still believe this to be a classpath error. (`java.lang.NoClassDefFoundError` indicates a class that was available at compile time is not present on your classpath)

In Java all classpath entries are combined and the first match is used. If you are using Maven for dependencies it will try to determine a single version for each library required, but unfortunately this does not always work flawlessly and sometimes it is just impossible.

As far as I'm aware depending on both Selenium 3 and 4 does not work properly (there are incompatible API changes and dependencies are quite different) so if your custom fixtures depend on Selenium 3 I don't think you can have them work in a single test run with tests using my fixtures (which require Selenium 4).

I believe the API changes from Selenium 3 -> 4 are not huge, so you probably easily can update your custom fixtures to Selenium 4.1.2 and then the situation will be easier (as the only Selenium 4 and its dependencies will be on the classpath).

In the past I also had trouble with the Maven classpath plugin and Selenium (even version 3) being on the same classpath, since they share a dependency on the same library but require different versions. This was only a problem in 'debug mode' and I was able to fix that by disabling the classpath plugin in those situations (it was not required it that case for me)

**Comment by aquddos123** [comment]
@fhoeben thank for the advise. I think I am in agreement with you. We'll upgrade Selenium and see how it goes.  
I have three more questions regarding this integration and then we can close this ticket. 

**Question #1:** 
Is there a possibility to reuse hsac Driver instance (which we are creating in SeleniumDriverSetup class) to power my old PageObjects? Currently, I am managing my own DriverFactory for older fixtures/PageObjects and I am thinking to reuse Plugin Driver instead of managing two different driver instances. I am thinking to use it in the following two ways, please suggest a better way if you there is any. 

One way is to extend all existing PageObjects with BrowserTest class to get access to Driver object and all other library functions like shown in the code snippet below.

```
	public class MyExistingPageObject extends BrowserTest {
		public boolean isReleaseModalDisplayed() {
			return this.getSeleniumHelper().driver().findElement(By.cssSelector("div.bx-yc--modal.is-visible")).isDisplayed();
		}
	}

```	

The other option (which I am leaning towards) is to get a hold on hsac plugin driver instance after it is instantiated and reuse with my existing fixtures/page objects. One possible way I implemented is given below. Please provide details if there is a better way to do so. 

```
public class PluginDriverHack <T extends WebElement> {
    private SeleniumHelper<T> seleniumHelper;
    private Environment environment = Environment.getInstance();

    protected Environment getEnvironment() {
        return this.environment;
    }

    private WebDriver driver() {
        return this.getEnvironment().getSeleniumHelper().driver();
    }

    protected SeleniumHelper<T> getSeleniumHelper() {
        return this.seleniumHelper;
    }
}

```
Then in setting driver instance in my existing DriverManager class as as below:

`DriverManager.setWebDriver(new PluginDriverHack().getEnvironment().getSeleniumHelper().driver());
`	

**Question #2:**
Is there a way to make a call to any method outside of hsac plugin code in the middle of a script and/or storyboard table? For example, after login to my app I need to call a method to generate and return OneTimePassword to complete 2FA step before going for any test steps. See  line 10 in the table below.

```
|script                |browser test                           |
|open                  |${APP_URL}                             |
|set browser size to maximum                                   |
|click                 |Login Credentials                      |
|seconds before timeout|2                                      |
|check                 |page title  |Login Credentials         |
|enter                 |${USERNAME} |as |css=#user-name-input  |
|enter                 |${PASSWORD} |as |css=#password-input   |
|click                 |css=#login-button                      |
|get                   |$TOTP = callLegacyCodeMethodToGetTOTP()|
|enter                 |${USERNAME} |as |css=#one-time-password|
|click                 |css=#submit                            |

``` 	

**Question #3:**
Does your system provision its own Selenium Hub on the fly when we use the below table or it requires a URL to an external running Selenium Hub? I believe the later is true but just wanted to verify.  

```
|script               |selenium driver setup|
|connect to driver for|chrome|at|${GRID_HUB}|
```

**Comment by fhoeben** [comment]
Question 1:
Both approaches could work. I would only use your first approach if inside your existing page objects there is a need/desire to use other BrowserTest methods. The second option seems better to be, but wouldn't it be even easier just to have your existing DriverManager class just call `Environment.getInstance().getSeleniumHelper().driver()` to initialise its static variable, or even simpler just make its method currently used by the page objects to get the driver delegate to that? I once wrote a 'bridge' that allowed me to run existing tests written using Xebium (another older Selenium/FitNesse fixture) using the Selenium driver provided by my own fixtures and augmenting there fixtures transparently with some of my features. Maybe that is interesting to look at for you? See https://github.com/fhoeben/hsac-xebium-bridge

Question 2:
Yes that is certainly possible. That is more a FitNesse question in general, nothing to do with these fixtures really. There are a couple of ways this can be achieved:
- you could have your special method be part of some fixture you setup to be a [library](http://fitnesse.org/FitNesse.UserGuide.WritingAcceptanceTests.SliM.LibraryTable). This means its methods can be called from any script all the time. This is quite practical for true utility methods (I use it sometimes for string manipulation methods) but doesn't seem a great fit for something as specific as a one time password
- you could just end the browser test script table, start a new table interacting with the fixture to get the OTP in a Slim variable and the start a new browser test script table where you use the Slim variable. This is the most straightforward approach (no 'magic' involved). The downside/limitation is that you cannot do that in a scenario (as it requires 3 separate script tables).
- you can use a little known feature called ['SlimHelperLibrary'](http://fitnesse.org/FitNesse.SuiteAcceptanceTests.SuiteSlimTests.ChainWithInstanceTest) that allows you to use the previous approach in a single table (therefore in a scenario also). It allows you to store the current fixture, activate a new fixture, use that and then return to the original fixture. It would look like:
```
|scenario|login as _ with _ and otp|username, password|
|enter                 |@{username}|as |css=#user-name-input  |
|enter                 |@{password} |as |css=#password-input   |
|click                 |css=#login-button                      |
|push fixture|
|start|otp fixture|
|$totp=|method of otp fixture to get totp|
|pop fixture|
|enter                 |$totp |as |css=#one-time-password|
|click                 |css=#submit                            |


|script                |browser test                           |
|open                  |${APP_URL}                             |
|set browser size to maximum                                   |
|click                 |Login Credentials                      |
|seconds before timeout|2                                      |
|check                 |page title  |Login Credentials         |
|login as|${USERNAME} |with|${PASSWORD} | and otp|
```

Question 3:
Indeed one has to supply their own Selenium grid using that approach. 


P.S.

On a side note when I look at your script for question 2 I notice some things. This may not reflect your real intended test code, but I do wanted to point the out, just to be safe:
- in general there is no need to set a shorter 'timeout' (e.g. `|seconds before timeout|2|`), the setting does not mean the fixtures wait 2 seconds everywhere it just means it will not wait *longer* than 2 seconds for each action, it is a failsafe. If it can be done quicker it will. So in general setting the timeout is only needed if you want to (temporarily) activate something you know will be quite slow
- you using CSS based 'technical selectors', while these work (and are fast) they also make for brittle tests (just like any technical selector they create a tight coupling between your test and the page's HTML). I really recommend you look at using the 'heuristic based selectors' which allow acceptance tests to be written that match an end user perspective of the page instead of a technical one. Using those one would write  `|enter |${USERNAME} |as |Username|` instead of `|enter |${USERNAME} |as |css=#user-name-input|`. The standard heuristics cover 'normal' HTML conventions and accessibility features, but you can also plug in your own if your application has different conventions (that does require a custom subclass of BrowserTest). I found that when you are part of the development effort of a new application the HTML usually gets better (also more screen reader friendly) if the pages are structured to make the [standard heuristics](https://raw.githubusercontent.com/fhoeben/hsac-fitnesse-fixtures/master/wiki/FitNesseRoot/HsacExamples/SlimTests/BrowserTests/FindingByHeuristics.wiki) work ;-)
- probably good to add a 'wait for visible ...' (or some other check) after logging in to ensure the login actually worked, so your test is aborted if logging in didn't work as expected :-)
