### ISSUE TITLE
Browser version dependency - a ticking bomb

### ISSUE THREAD

**Issue by aquddos123** [fhoeben/hsac-fitnesse-fixtures#419]
I see most of the new releases of this project are to coup the version updates of Chrome and Edge browsers. This type of dependencies especially on browser versions can easily jeopardize one's efforts and leave them in a dead end if/when the project is not maintained in the long run.
 
Is it possible to make this project independent of browser and selenium versions and leave this burden on the plugin user to arrange compatible browser drivers?
Like some versions of Selenium does not work well with some versions of browsers but that is not Selenium issue rather browser side issue and the Selenium users know what to do to make it compatible with their custom projects.

We had a bad experience with a similar project/plugin in the past, https://mvnrepository.com/artifact/uk.co.javahelp.fitnesse/fitnesse-launcher-maven-plugin. They had a dependency on Selenium 2.x and stopped maintaining the project at one point and we had no option but to reconfigure our regression suites. 

https://mvnrepository.com/artifact/org.fitnesse.plugins/maven-classpath-plugin is another good example, not well maintained and the projects using this plugin are struggling with a lot of Guava and other dependencies issues. 

So my suggestion is to try to make this project long lasting. These modern browsers are keep on changing a lot and it should not be your responsibility to take care all this.

**Comment by fhoeben** [comment]
@aquddos123 thanks for the concern and thinking about making the project long lasting. I understand your worries and have experienced similar issues (this project was using maven-classpath-plugin also).

But I do believe the current approach of bundling webdriver is good to keep up. Strictly speaking the project's fixtures do not depend on using these drivers. The fixtures for browser testing depend on Selenium which requires a connection to a browser (the other fixtures do not need/use Selenium or webdrivers at all). 

We only include the webdrivers in the `...-standalone.zip` package provided by this project so people can download it and get started using their locally installed browser, which ('thanks to' the automatic update feature of modern browsers) mostly requires the most recent webdriver for Selenium to connect to it. Otherwise we would have to maintain installation instructions (OS specific) to get these, and in projects where many people work on the tests each person would have to do so manually for their own machine.

There is nothing special about these webdrivers, if you don't want to be dependent on them you can configure the 'selenium driver setup' in your SuiteSetUp page to use whatever selenium configuration/webdriver you want. You could for instance use a Selenium grid (which will not require any webdrivers to run the tests, only on the machines running the browsers), or use a Selenium/webdriver combo that has been previously (manually) installed somewhere on the machine running the tests.
An example (and proof that it works) of the latter approach, having the browser and webdrivers installed locally independently of what is in the `pom.xml` of the project can be seen in the docker containers created by this project. Those just take virtual machines from the Selenium project, which have Java, Chrome and a compatible webdriver installed, and only add the fixture .jars. These virtual machines (images) can then just get some wiki pages and are able to run tests. They do not get any webdrivers from this project, so the version selected in this project is not important. (Actually this is why I always recommend running your integration tests in CI pipelines using docker images (or other virtual machines), since these provide you stable browser/webdriver combinations which is hard to achieve otherwise.)

We have taken on the 'best effort' responsibility of providing a ready-to-use/it-just-works local setup for test projects, which requires use to track browser releases. But this is just a minor convenience feature we offer. It is in no way part of this project's core and if we fail to keep up with these releases all users should be able to switch, at that point in time, to using exactly the approach you suggest we should force them to start using today (i.e. "leave this burden on the plugin user to arrange compatible browser drivers?"). Plugin users are completely enabled by us to take on this burden themselves (and they probably have for their CI runs). Should they want to take it on already for their local environments they can. Making it easy for them requires little effort from us (just updating a version number and having the automatic GitHub action create a new release) so we choose to do so.
