### ISSUE TITLE
Images only available as ARM64

### ISSUE THREAD

**Issue by DLeijenKeylane** [fhoeben/hsac-fitnesse-fixtures#553]
Checking https://hub.docker.com/r/hsac/fitnesse-fixtures-test-jre11-chrome/tags to test our upgrade, I noticed there are only ARM64 images available, no AMD64.

Will this be changed in the future?

**Comment by fhoeben** [comment]
I hope there will be. They are not currently there because of an issue in the GitLab pipeline to push them to docker hub.

For now you should be able to get them from GitLab's registry: 

* registry.gitlab.com/hsac-fitnesse/hsac-fitnesse-fixtures/fitnesse-fixtures-test-jre11:latest
* registry.gitlab.com/hsac-fitnesse/hsac-fitnesse-fixtures/fitnesse-fixtures-test-jre11-with-pdf:latest
* registry.gitlab.com/hsac-fitnesse/hsac-fitnesse-fixtures/fitnesse-fixtures-test-jre11-chrome:latest
* registry.gitlab.com/hsac-fitnesse/hsac-fitnesse-fixtures/fitnesse-fixtures-test-jre11-chrome-with-pdf:latest
* registry.gitlab.com/hsac-fitnesse/hsac-fitnesse-fixtures/fitnesse-fixtures-combine:latest

**Comment by fhoeben** [comment]
I believe the images are uploaded now
