### ISSUE TITLE
How to from $drmName get text uncle?

### ISSUE THREAD

**Issue by cmaster007** [fhoeben/hsac-fitnesse-fixtures#582]
eg:
|$drmName=|vlaue of|id=name|
result:
$drmName<-[uncle]

How to from $drmName get text uncle?

|execute javascript    |setTimeout(function() {   print(wait)}, 5000)|until|id=name|is not|uncle|

**Comment by fhoeben** [comment]
I would think

`|execute javascript |setTimeout(function() { print(wait)}, 5000)|until|id=name|is not|$drmName |`

Although I assume the JavaScript function can be a bit smarter (one can use something like `|set repeat interval to|5000|milliseconds|`) because I believe `setTimeout` returns immediately so you never see the effect of the function being evaluated and you are scheduling a new delayed function call on each repeat interval (default 100ms).

Even if it were very slow I would expect something like:
```
|set repeat interval to|1000|milliseconds|
|repeat at most        |200                  |times                    |
|execute javascript |console.log('waiting')|until|id=name|is not|$drmName |
|show                 |repeat count |
|show|value of|id=name|
```

**Comment by cmaster007** [comment]
Thank  you
