### ISSUE TITLE
set header value for BrowserTest script?

### ISSUE THREAD

**Issue by violinner** [fhoeben/hsac-fitnesse-fixtures#74]
Is it possible to set headers for subsequent "open url" commands in BrowserTest scripts,
to avoid the redirect and delay of a login screen?

This works with "xml http test", but apparently not with "BrowserTest."

**Comment by fhoeben** [comment]
Explicitly setting headers is not currently a feature supported by BrowserTest (as real web browsers also don't offer this).

What is the test setup/flow you want to use this for. What I sometimes do is: log in via a SuiteSetUp and all pages in that suite can use browser test as that logged in user, logging out is done in the SuiteTearDown.

Since by default we don't kill browser windows, delete cookies, clear local storage or anything like that, between invocations of BrowserTest the security context does not disappear (unless you remove it). So I would expect that a new "open url" line keeps the same context as existed before.
Having said that I assume the security context is kept using cookies, not explicitly via headers.

This behavior of 'open url' is what users normally experience when they click on a link for applications:
- if they are logged in: the page is opened immediately
- if they are not logged in the page is not opened (if it is a 'nice' application they are taken to a login screen and after successful login the page is opened for them)

**Comment by violinner** [comment]
Thank you for your response!
On a login page, When a user account has a dot (.) in the password, this
shows as a link to a non-existent page in the script ([?]).
How can I escape that and enter values.with.dots for login user names and
passwords?

Thanks
Joel

**Comment by violinner** [comment]
My mistake- when the value for "|enter|${value}|as..." begins with a
capital letter and ends with a number, it does up as a link to a
non-existent page. Can I escape this?
Thanks again!

**Comment by fhoeben** [comment]
Try using !- and -!, for instance: `!-MyUserName21-!`, see http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.MarkupLanguageReference.MarkupLiteralText
